# Generated by Django 3.1.1 on 2020-09-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newinsta', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
