# Generated by Django 3.1.1 on 2020-09-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newinsta', '0005_userdata_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='post',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
    ]
