# Generated by Django 3.1.1 on 2020-09-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newinsta', '0006_auto_20200908_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
