# Generated by Django 3.1.1 on 2020-09-09 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newinsta', '0007_userdata_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='currentdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
