# Generated by Django 3.1.1 on 2020-09-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newinsta', '0008_userdata_currentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='currentdate',
        ),
    ]
