# Generated by Django 3.1.1 on 2020-09-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newinsta', '0009_remove_userdata_currentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
